Spectre: spectre Namespace Reference
spectre Namespace Reference
Classes
class App
struct AppConfig
struct AppOptions
struct AtlasDirtyRect
struct AtlasRegion
struct CapturedFrame
struct Cell
struct CellUpdate
struct Color
struct CursorStyle
class FontManager
struct FontMetrics
class GlyphCache
struct GpuCell
class Grid
class GridRenderingPipeline
class HighlightTable
struct HlAttr
class IGridSink
class IRenderer
class IRpcChannel
class IWindow
struct KeyEvent
struct LogOptions
struct LogRecord
class MetalRenderer
struct ModeInfo
struct MouseButtonEvent
struct MouseMoveEvent
struct MouseWheelEvent
struct MpackValue
class NvimInput
class NvimProcess
class NvimRpc
class RendererState
struct RenderTestScenario
struct RpcNotification
struct RpcResponse
struct RpcResult
class SdlWindow
struct ShapedGlyph
struct SwapchainInfo
struct TextEditingEvent
struct TextInputEvent
class TextService
struct TextServiceConfig
class TextShaper
class UiEventHandler
struct UiOptions
class UiRequestWorker
struct UnicodeRange
class VkAtlas
class VkContext
class VkGridBuffer
class VkPipelineManager
class VkRenderer
class VkStagingBuffer
struct WindowResizeEvent
Typedefs
using LogSink = std::function< void(const LogRecord &)>
Enumerations
enum class LogLevel {
Error = 0 , Warn = 1 , Info = 2 , Debug = 3 ,
Trace = 4
}
enum class LogCategory {
App , Rpc , Nvim , Window ,
Font , Renderer , Input , Test
}
enum class AmbiWidth { Single , Double }
enum class CursorShape { Block , Horizontal , Vertical }
Functions
std::optional< RenderTestScenario > load_render_test_scenario (const std::filesystem::path &path, std::string *error_message=nullptr)
bool export_render_test_frame (const std::filesystem::path &path, const CapturedFrame &frame, std::string *error_message=nullptr)
bool finalize_render_test_result (const RenderTestScenario &scenario, const CapturedFrame &frame, bool bless_reference, std::string *error_message=nullptr)
void write_render_test_failure_report (const RenderTestScenario &scenario, std::string_view error_message)
bool encode_mpack_value (const MpackValue &value, std::vector< char > &out)
bool decode_mpack_value (std::span< const uint8_t > bytes, MpackValue &value, size_t *consumed=nullptr)
bool encode_rpc_request (uint32_t msgid, const std::string &method, const std::vector< MpackValue > &params, std::vector< char > &out)
bool encode_rpc_notification (const std::string &method, const std::vector< MpackValue > &params, std::vector< char > &out)
std::unique_ptr< IRenderer > create_renderer ()
void configure_logging (LogOptions options={})
void configure_default_logging (const char *default_file_name="spectre.log", bool prefer_file_when_no_console=true)
void shutdown_logging ()
bool log_would_emit (LogLevel level, LogCategory category)
void set_log_sink (LogSink sink)
void clear_log_sink ()
void log_message (LogLevel level, LogCategory category, std::string_view message)
void log_printf (LogLevel level, LogCategory category, const char *fmt,...)
const char * to_string (LogLevel level)
const char * to_string (LogCategory category)
template<size_t N>
constexpr bool in_ranges (uint32_t cp, const std::array< UnicodeRange, N > &ranges)
bool utf8_decode_next (std::string_view text, size_t &offset, uint32_t &cp)
uint32_t utf8_first_codepoint (std::string_view text)
bool is_east_asian_wide (uint32_t cp)
bool is_east_asian_ambiguous (uint32_t cp)
bool is_default_emoji_presentation (uint32_t cp)
bool is_emoji_text_presentation_candidate (uint32_t cp)
bool is_width_ignorable (uint32_t cp)
bool is_regional_indicator (uint32_t cp)
bool is_emoji_modifier (uint32_t cp)
bool is_ascii_keycap_base (uint32_t cp)
int cluster_cell_width (std::string_view text, const UiOptions &options={})
Variables
constexpr int GLYPH_ATLAS_SIZE = 2048
constexpr uint32_t STYLE_FLAG_BOLD = 1u << 0
constexpr uint32_t STYLE_FLAG_ITALIC = 1u << 1
constexpr uint32_t STYLE_FLAG_UNDERLINE = 1u << 2
constexpr uint32_t STYLE_FLAG_STRIKETHROUGH = 1u << 3
constexpr uint32_t STYLE_FLAG_UNDERCURL = 1u << 4
constexpr uint32_t STYLE_FLAG_COLOR_GLYPH = 1u << 5
Typedef Documentation
LogSink
using spectre::LogSink = typedef std::function<void(const LogRecord&)>
Definition at line 48 of file log.h.
Enumeration Type Documentation
AmbiWidth
enum class spectre::AmbiWidth strong
Enumerator
Single
Double
Definition at line 45 of file types.h.
CursorShape
enum class spectre::CursorShape strong
Enumerator
Block
Horizontal
Vertical
Definition at line 56 of file types.h.
LogCategory
enum class spectre::LogCategory strong
Enumerator
App
Rpc
Nvim
Window
Font
Renderer
Input
Test
Definition at line 20 of file log.h.
LogLevel
enum class spectre::LogLevel strong
Enumerator
Error
Warn
Info
Debug
Trace
Definition at line 11 of file log.h.
Function Documentation
clear_log_sink()
void spectre::clear_log_sink ()
cluster_cell_width()
int spectre::cluster_cell_width (std::string_view text, const UiOptions & options = {}) inline
Definition at line 445 of file unicode.h.
configure_default_logging()
void spectre::configure_default_logging (const char * default_file_name = "spectre.log", bool prefer_file_when_no_console = true)
configure_logging()
void spectre::configure_logging (LogOptions options = {})
create_renderer()
std::unique_ptr< IRenderer > spectre::create_renderer ()
decode_mpack_value()
bool spectre::decode_mpack_value (std::span< const uint8_t > bytes, MpackValue & value, size_t * consumed = nullptr)
encode_mpack_value()
bool spectre::encode_mpack_value (const MpackValue & value, std::vector< char > & out)
encode_rpc_notification()
bool spectre::encode_rpc_notification (const std::string & method, const std::vector< MpackValue > & params, std::vector< char > & out)
encode_rpc_request()
bool spectre::encode_rpc_request (uint32_t msgid, const std::string & method, const std::vector< MpackValue > & params, std::vector< char > & out)
export_render_test_frame()
bool spectre::export_render_test_frame (const std::filesystem::path & path, const CapturedFrame & frame, std::string * error_message = nullptr)
finalize_render_test_result()
bool spectre::finalize_render_test_result (const RenderTestScenario & scenario, const CapturedFrame & frame, bool bless_reference, std::string * error_message = nullptr)
in_ranges()
template<size_t N> constexpr bool spectre::in_ranges (uint32_t cp, const std::array< UnicodeRange, N > & ranges) constexpr
Definition at line 19 of file unicode.h.
Referenced by is_default_emoji_presentation(), is_east_asian_ambiguous(), is_emoji_text_presentation_candidate(), and is_width_ignorable().
is_ascii_keycap_base()
bool spectre::is_ascii_keycap_base (uint32_t cp) inline
Definition at line 440 of file unicode.h.
is_default_emoji_presentation()
bool spectre::is_default_emoji_presentation (uint32_t cp) inline
Definition at line 304 of file unicode.h.
References in_ranges().
is_east_asian_ambiguous()
bool spectre::is_east_asian_ambiguous (uint32_t cp) inline
Definition at line 134 of file unicode.h.
References in_ranges().
is_east_asian_wide()
bool spectre::is_east_asian_wide (uint32_t cp) inline
Definition at line 124 of file unicode.h.
is_emoji_modifier()
bool spectre::is_emoji_modifier (uint32_t cp) inline
Definition at line 435 of file unicode.h.
is_emoji_text_presentation_candidate()
bool spectre::is_emoji_text_presentation_candidate (uint32_t cp) inline
Definition at line 357 of file unicode.h.
References in_ranges().
is_regional_indicator()
bool spectre::is_regional_indicator (uint32_t cp) inline
Definition at line 430 of file unicode.h.
is_width_ignorable()
bool spectre::is_width_ignorable (uint32_t cp) inline
Definition at line 391 of file unicode.h.
References in_ranges().
load_render_test_scenario()
std::optional< RenderTestScenario > spectre::load_render_test_scenario (const std::filesystem::path & path, std::string * error_message = nullptr)
log_message()
void spectre::log_message (LogLevel level, LogCategory category, std::string_view message)
log_printf()
void spectre::log_printf (LogLevel level, LogCategory category, const char * fmt, ...)
log_would_emit()
bool spectre::log_would_emit (LogLevel level, LogCategory category)
set_log_sink()
void spectre::set_log_sink (LogSink sink)
shutdown_logging()
void spectre::shutdown_logging ()
to_string() [1/2]
const char * spectre::to_string (LogCategory category)
to_string() [2/2]
const char * spectre::to_string (LogLevel level)
utf8_decode_next()
bool spectre::utf8_decode_next (std::string_view text, size_t & offset, uint32_t & cp) inline
Definition at line 29 of file unicode.h.
Referenced by utf8_first_codepoint().
utf8_first_codepoint()
uint32_t spectre::utf8_first_codepoint (std::string_view text) inline
Definition at line 113 of file unicode.h.
References utf8_decode_next().
write_render_test_failure_report()
void spectre::write_render_test_failure_report (const RenderTestScenario & scenario, std::string_view error_message)
Variable Documentation
GLYPH_ATLAS_SIZE
constexpr int spectre::GLYPH_ATLAS_SIZE = 2048 inline constexpr
Definition at line 8 of file types.h.
STYLE_FLAG_BOLD
constexpr uint32_t spectre::STYLE_FLAG_BOLD = 1u << 0 inline constexpr
Definition at line 72 of file types.h.
STYLE_FLAG_COLOR_GLYPH
constexpr uint32_t spectre::STYLE_FLAG_COLOR_GLYPH = 1u << 5 inline constexpr
Definition at line 77 of file types.h.
STYLE_FLAG_ITALIC
constexpr uint32_t spectre::STYLE_FLAG_ITALIC = 1u << 1 inline constexpr
Definition at line 73 of file types.h.
STYLE_FLAG_STRIKETHROUGH
constexpr uint32_t spectre::STYLE_FLAG_STRIKETHROUGH = 1u << 3 inline constexpr
Definition at line 75 of file types.h.
STYLE_FLAG_UNDERCURL
constexpr uint32_t spectre::STYLE_FLAG_UNDERCURL = 1u << 4 inline constexpr
Definition at line 76 of file types.h.
STYLE_FLAG_UNDERLINE
constexpr uint32_t spectre::STYLE_FLAG_UNDERLINE = 1u << 2 inline constexpr
Definition at line 74 of file types.h.